ALTER TABLE T_TREND_RUN
  ADD COLUMN IS_PUBLISHED TINYINT(1) NOT NULL DEFAULT 1 AFTER TOP_N,
  ADD COLUMN PUBLISHED_AT DATETIME NULL DEFAULT NULL AFTER IS_PUBLISHED,
  ADD KEY IX_T_TREND_RUN__IS_PUBLISHED (IS_PUBLISHED);

UPDATE T_TREND_RUN
   SET PUBLISHED_AT = COALESCE(PUBLISHED_AT, RUN_AT)
 WHERE IS_PUBLISHED = 1;
