-- data-pipeline/db/newsight_verify.sql
-- Newsight 데이터 적재/분석 결과 검증용 SQL 모음 (MySQL 8.x / utf8mb4)
-- 사용법:
-- 1) 아래 @run_seq 값을 상황에 맞게 설정
-- 2) 섹션별로 실행하면서 "0건이 정상" / "개수/합계가 기대와 일치" 여부를 확인
-- 참고: DBeaver에서 SQL 쿼리 실행할 땐 쿼리 전체를 드래그해서 선택한 후 Ctrl+Enter로 실행

/* ----------------------------------------------------------------------
  0) 공통: 검사 기준 run 변수 세팅
  - 기간(TODAY/D7/D14)은 BASE_DATE 기준 윈도우로 쿼리 내부에서 계산한다(변수 미사용).
  - TODAY 윈도우: [BASE_DATE 00:00:00, BASE_DATE + 1day 00:00:00)
  - D7    윈도우: [BASE_DATE - 6day 00:00:00, BASE_DATE + 1day 00:00:00)  (오늘 포함 7일)
  - D14   윈도우: [BASE_DATE - 13day 00:00:00, BASE_DATE + 1day 00:00:00) (오늘 포함 14일)
------------------------------------------------------------------------ */

-- 최신 run 기준으로 검증
SET @run_seq := (SELECT MAX(TREND_RUN_SEQ) FROM T_TREND_RUN);

-- 특정 run 지정 시 주석 해제 후 값만 수정
-- SET @run_seq := 11;


/* ----------------------------------------------------------------------
  1) T_NEWS_MEDIA (언론사)
------------------------------------------------------------------------ */

-- 1) 시드가 정상인지(전체 포함)
SELECT * FROM T_NEWS_MEDIA ORDER BY MEDIA_CODE;

-- 2) MEDIA_CODE 중복/이상 여부(원래 PK라 0건이 정상)
SELECT MEDIA_CODE, COUNT(*) AS cnt
FROM T_NEWS_MEDIA
GROUP BY MEDIA_CODE
HAVING cnt > 1;

-- 3) 기사/분석 테이블에 존재하는 MEDIA_CODE가 모두 마스터에 있는지(0건 정상)
-- 주의: MEDIA_CODE=0(전체 집계 행)을 사용하는 테이블이 있다면, 마스터에 0이 없을 수 있으므로 제외한다.
SELECT a.MEDIA_CODE, COUNT(*) AS cnt
FROM (
  SELECT MEDIA_CODE FROM T_NEWS_ARTICLE
  UNION ALL SELECT MEDIA_CODE FROM T_ANALYZE_MEDIA_STAT
  UNION ALL SELECT MEDIA_CODE FROM T_ANALYZE_SENTIMENT
  UNION ALL SELECT MEDIA_CODE FROM T_ANALYZE_MEDIA_BIAS
  UNION ALL SELECT MEDIA_CODE FROM T_ANALYZE_WORDCLOUD
  UNION ALL SELECT MEDIA_CODE FROM T_ANALYZE_CO_MENTION_GRAPH
) a
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = a.MEDIA_CODE
WHERE a.MEDIA_CODE IS NOT NULL
  AND a.MEDIA_CODE <> 0
  AND m.MEDIA_CODE IS NULL
GROUP BY a.MEDIA_CODE;


/* ----------------------------------------------------------------------
  2) T_TREND_KEYWORD_MASTER (키워드 마스터)
------------------------------------------------------------------------ */

-- 1) 키워드 총량/최근 생성 날짜
SELECT COUNT(*) AS keyword_cnt, MAX(CREATED_AT) AS last_created_at
FROM T_TREND_KEYWORD_MASTER;

-- 2) KEYWORD_NAME 중복(0건 정상: UNIQUE)
SELECT KEYWORD_NAME, COUNT(*) AS cnt
FROM T_TREND_KEYWORD_MASTER
GROUP BY KEYWORD_NAME
HAVING cnt > 1;

-- 3) 키워드명 공백/이상치(0건 정상)
SELECT KEYWORD_SEQ, KEYWORD_NAME
FROM T_TREND_KEYWORD_MASTER
WHERE KEYWORD_NAME IS NULL OR TRIM(KEYWORD_NAME) = '';


/* ----------------------------------------------------------------------
  3) T_TREND_RUN (트렌드 실행)
------------------------------------------------------------------------ */

-- 1) 최신 run 목록 확인
SELECT TREND_RUN_SEQ, BASE_DATE, RUN_AT, TOP_N
FROM T_TREND_RUN
ORDER BY TREND_RUN_SEQ DESC
LIMIT 20;

-- 1-1) 특정 TREND_RUN_SEQ의 키워드 목록(순위 포함)
SELECT
  s.TREND_RUN_SEQ,
  s.TREND_RANK,
  s.KEYWORD_SEQ,
  km.KEYWORD_NAME
FROM T_TREND_KEYWORD_SNAPSHOT s
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = s.KEYWORD_SEQ
WHERE s.TREND_RUN_SEQ = @run_seq
ORDER BY s.TREND_RANK ASC;

-- 2) 같은 BASE_DATE가 여러 run으로 쌓였는지(정상일 수도 있음)
-- 예를들어 하루에 여러번 크롤링 및 분석 돌리면 cnt가 1보다 큼
SELECT BASE_DATE,
       COUNT(*) AS cnt,
       MIN(TREND_RUN_SEQ) AS min_trend_run_seq,
       MAX(TREND_RUN_SEQ) AS max_trend_run_seq
FROM T_TREND_RUN
GROUP BY BASE_DATE
ORDER BY BASE_DATE DESC
LIMIT 30;


/* ----------------------------------------------------------------------
  4) T_TREND_KEYWORD_SNAPSHOT (트렌드 스냅샷)
------------------------------------------------------------------------ */

-- 1) run별 스냅샷 행 수(Top N 개수와 맞는지)
SELECT TREND_RUN_SEQ,
       COUNT(*) AS snapshot_cnt,
       MIN(TREND_RANK) AS min_rank,
       MAX(TREND_RANK) AS max_rank
FROM T_TREND_KEYWORD_SNAPSHOT
GROUP BY TREND_RUN_SEQ
ORDER BY TREND_RUN_SEQ DESC
LIMIT 20;

-- 2) 현재 run(@run_seq)의 rank 연속성 체크(빠진 순위가 있는지)
-- 0건 정상
-- (개선) 1..MAX(TREND_RANK)까지 동적으로 생성해서 200 고정 한계를 제거
WITH RECURSIVE seq AS (
  SELECT 1 AS n
  UNION ALL
  SELECT n + 1
  FROM seq
  WHERE n < (
    SELECT COALESCE(MAX(TREND_RANK), 0)
    FROM T_TREND_KEYWORD_SNAPSHOT
    WHERE TREND_RUN_SEQ = @run_seq
  )
)
SELECT seq.n AS missing_rank
FROM seq
LEFT JOIN T_TREND_KEYWORD_SNAPSHOT s
  ON s.TREND_RUN_SEQ = @run_seq AND s.TREND_RANK = seq.n
WHERE s.TREND_RANK IS NULL
ORDER BY missing_rank;

-- 3) 중복(0건 정상: UNIQUE 제약)
SELECT TREND_RUN_SEQ, TREND_RANK, COUNT(*) AS cnt
FROM T_TREND_KEYWORD_SNAPSHOT
GROUP BY TREND_RUN_SEQ, TREND_RANK
HAVING cnt > 1;

SELECT TREND_RUN_SEQ, KEYWORD_SEQ, COUNT(*) AS cnt
FROM T_TREND_KEYWORD_SNAPSHOT
GROUP BY TREND_RUN_SEQ, KEYWORD_SEQ
HAVING cnt > 1;

-- 4) 스냅샷이 참조하는 키워드가 마스터에 있는지(0건 정상)
SELECT s.*
FROM T_TREND_KEYWORD_SNAPSHOT s
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = s.KEYWORD_SEQ
WHERE s.TREND_RUN_SEQ = @run_seq AND k.KEYWORD_SEQ IS NULL;


/* ----------------------------------------------------------------------
  5) T_NEWS_ARTICLE (기사)
------------------------------------------------------------------------ */

-- 1) 특정 run(@run_seq): 키워드별 기사 수(기간 조건 없음)
-- 0건인 기사는 안 뜬다.
SELECT
  a.TREND_RUN_SEQ,
  a.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  COUNT(*) AS article_cnt,
  MIN(a.PUBLISHED_AT) AS min_published_at,
  MAX(a.PUBLISHED_AT) AS max_published_at
FROM T_NEWS_ARTICLE a
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = a.KEYWORD_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, km.KEYWORD_NAME
ORDER BY article_cnt DESC;


-- 2) 언론사별 기사 수(기간 조건 없음: run에 적재된 전체 -> 사실상 D14 기준)
SELECT t.MEDIA_CODE,
       COALESCE(m.MEDIA_NAME, CASE WHEN t.MEDIA_CODE = 0 THEN '전체' ELSE NULL END) AS MEDIA_NAME,
       t.article_cnt
FROM (
  SELECT 0 AS MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE
  WHERE TREND_RUN_SEQ = @run_seq

  UNION ALL

  SELECT MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE
  WHERE TREND_RUN_SEQ = @run_seq
  GROUP BY MEDIA_CODE
) AS t
LEFT JOIN T_NEWS_MEDIA AS m ON m.MEDIA_CODE = t.MEDIA_CODE
ORDER BY (t.MEDIA_CODE = 0) DESC, t.article_cnt DESC;

-- 2-1) 언론사별 TODAY 기사 수(BASE_DATE 기준)
SELECT t.MEDIA_CODE,
       COALESCE(m.MEDIA_NAME, CASE WHEN t.MEDIA_CODE = 0 THEN '전체' ELSE NULL END) AS MEDIA_NAME,
       t.article_cnt
FROM (
  SELECT 0 AS MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))

  UNION ALL

  SELECT a.MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.MEDIA_CODE
) AS t
LEFT JOIN T_NEWS_MEDIA AS m ON m.MEDIA_CODE = t.MEDIA_CODE
ORDER BY (t.MEDIA_CODE = 0) DESC, t.article_cnt DESC;

-- 2-2) 언론사별 D7 기사 수(BASE_DATE 기준, 오늘 포함 7일)
SELECT t.MEDIA_CODE,
       COALESCE(m.MEDIA_NAME, CASE WHEN t.MEDIA_CODE = 0 THEN '전체' ELSE NULL END) AS MEDIA_NAME,
       t.article_cnt
FROM (
  SELECT 0 AS MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))

  UNION ALL

  SELECT a.MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.MEDIA_CODE
) AS t
LEFT JOIN T_NEWS_MEDIA AS m ON m.MEDIA_CODE = t.MEDIA_CODE
ORDER BY (t.MEDIA_CODE = 0) DESC, t.article_cnt DESC;

-- 2-3) 언론사별 D14 기사 수(BASE_DATE 기준, 오늘 포함 14일)
SELECT t.MEDIA_CODE,
       COALESCE(m.MEDIA_NAME, CASE WHEN t.MEDIA_CODE = 0 THEN '전체' ELSE NULL END) AS MEDIA_NAME,
       t.article_cnt
FROM (
  SELECT 0 AS MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))

  UNION ALL

  SELECT a.MEDIA_CODE, COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.MEDIA_CODE
) AS t
LEFT JOIN T_NEWS_MEDIA AS m ON m.MEDIA_CODE = t.MEDIA_CODE
ORDER BY (t.MEDIA_CODE = 0) DESC, t.article_cnt DESC;

-- 3) 키워드별 기사 수(기간조건 없음 -> 사실상 D14 기준)
SELECT
  a.KEYWORD_SEQ,
  k.KEYWORD_NAME,
  COUNT(*) AS article_cnt
FROM T_NEWS_ARTICLE a
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = a.KEYWORD_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
GROUP BY a.KEYWORD_SEQ, k.KEYWORD_NAME
ORDER BY article_cnt DESC, a.KEYWORD_SEQ ASC;

-- 3-1) 키워드별 TODAY 기사 수(BASE_DATE 기준)
SELECT
  a.KEYWORD_SEQ,
  k.KEYWORD_NAME,
  COUNT(*) AS article_cnt
FROM T_NEWS_ARTICLE a
JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = a.KEYWORD_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
  AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
  AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
GROUP BY a.KEYWORD_SEQ, k.KEYWORD_NAME
ORDER BY article_cnt DESC, a.KEYWORD_SEQ ASC;

-- 3-2) 키워드별 D7 기사 수(BASE_DATE 기준, 오늘 포함 7일)
SELECT
  a.KEYWORD_SEQ,
  k.KEYWORD_NAME,
  COUNT(*) AS article_cnt
FROM T_NEWS_ARTICLE a
JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = a.KEYWORD_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
  AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
  AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
GROUP BY a.KEYWORD_SEQ, k.KEYWORD_NAME
ORDER BY article_cnt DESC, a.KEYWORD_SEQ ASC;

-- 3-3) 키워드별 D14 기사 수(BASE_DATE 기준, 오늘 포함 14일)
SELECT
  a.KEYWORD_SEQ,
  k.KEYWORD_NAME,
  COUNT(*) AS article_cnt
FROM T_NEWS_ARTICLE a
JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = a.KEYWORD_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
  AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
  AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
GROUP BY a.KEYWORD_SEQ, k.KEYWORD_NAME
ORDER BY article_cnt DESC, a.KEYWORD_SEQ ASC;

-- 4) URL_HASH 중복(0건 정상: UNIQUE(RUN,KEYWORD,URL_HASH))
SELECT TREND_RUN_SEQ, KEYWORD_SEQ, URL_HASH, COUNT(*) AS cnt
FROM T_NEWS_ARTICLE
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, KEYWORD_SEQ, URL_HASH
HAVING cnt > 1;

-- 5) 필수값 누락/이상치 점검(0건 정상)
SELECT ARTICLE_SEQ, SOURCE_URL, URL_HASH, TITLE, MEDIA_CODE, KEYWORD_SEQ, TREND_RUN_SEQ
FROM T_NEWS_ARTICLE
WHERE TREND_RUN_SEQ = @run_seq
  AND (
    SOURCE_URL IS NULL OR TRIM(SOURCE_URL) = ''
    OR URL_HASH IS NULL OR CHAR_LENGTH(URL_HASH) <> 64
    OR TITLE IS NULL OR TRIM(TITLE) = ''
  )
LIMIT 200;

-- 5-1) URL_HASH 포맷이 64 hex가 아닌 경우(0건 정상)
SELECT ARTICLE_SEQ, URL_HASH
FROM T_NEWS_ARTICLE
WHERE TREND_RUN_SEQ = @run_seq
  AND (URL_HASH IS NULL OR URL_HASH NOT REGEXP '^[0-9a-fA-F]{64}$')
LIMIT 200;

-- 6) 전처리 상태 점검(클린 컬럼 결측 수)
-- 0건 정상
SELECT
  SUM(CASE WHEN TITLE_CLEAN IS NULL OR TRIM(TITLE_CLEAN) = '' THEN 1 ELSE 0 END) AS title_clean_missing,
  SUM(CASE WHEN CONTENT_CLEAN IS NULL OR TRIM(CONTENT_CLEAN) = '' THEN 1 ELSE 0 END) AS content_clean_missing,
  COUNT(*) AS total
FROM T_NEWS_ARTICLE
WHERE TREND_RUN_SEQ = @run_seq;

-- 7) 기사 FK 무결성(원칙상 0건)
SELECT a.ARTICLE_SEQ
FROM T_NEWS_ARTICLE a
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = a.MEDIA_CODE
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = a.KEYWORD_SEQ
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
  AND (m.MEDIA_CODE IS NULL OR k.KEYWORD_SEQ IS NULL OR r.TREND_RUN_SEQ IS NULL)
LIMIT 200;


/* ----------------------------------------------------------------------
  6) T_NEWS_COMMENT (댓글)
------------------------------------------------------------------------ */

-- 1) 기사당 댓글 수 분포(상위)
SELECT ARTICLE_SEQ, COUNT(*) AS comment_cnt
FROM T_NEWS_COMMENT
GROUP BY ARTICLE_SEQ
ORDER BY comment_cnt DESC
LIMIT 50;

-- 2) 중복 댓글(0건 정상: UNIQUE(ARTICLE_SEQ, COMMENT_HASH))
SELECT ARTICLE_SEQ, COMMENT_HASH, COUNT(*) AS cnt
FROM T_NEWS_COMMENT
GROUP BY ARTICLE_SEQ, COMMENT_HASH
HAVING cnt > 1;

-- 3) 고아 댓글(원칙상 0건: 기사 FK)
SELECT c.COMMENT_SEQ, c.ARTICLE_SEQ
FROM T_NEWS_COMMENT c
LEFT JOIN T_NEWS_ARTICLE a ON a.ARTICLE_SEQ = c.ARTICLE_SEQ
WHERE a.ARTICLE_SEQ IS NULL
LIMIT 200;

-- 4) 전처리 상태 점검(0건이 이상적 목표이긴 하나 케이스에 따라 0이 아닐 수 있음)
-- 예를들어 이모티콘 등만 있는 댓글 같은 경우
-- (개선) run 기준으로만 집계해서 "이번 run" 품질을 정확히 보기
SELECT
  SUM(CASE WHEN c.COMMENT_CLEAN IS NULL OR TRIM(c.COMMENT_CLEAN) = '' THEN 1 ELSE 0 END) AS comment_clean_missing,
  COUNT(*) AS total
FROM T_NEWS_COMMENT c
JOIN T_NEWS_ARTICLE a ON a.ARTICLE_SEQ = c.ARTICLE_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq;


/* ----------------------------------------------------------------------
  7) T_TREND_KEYWORD_FINAL_RANK (최종 순위)
------------------------------------------------------------------------ */

-- 1) run/period 별 최종 순위 개수/최대랭크
SELECT TREND_RUN_SEQ, PERIOD_FILTER,
       COUNT(*) AS rows_cnt,
       MIN(FINAL_RANK) AS min_rank,
       MAX(FINAL_RANK) AS max_rank
FROM T_TREND_KEYWORD_FINAL_RANK
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER;

-- 2) FINAL_RANK 중복(0건이 이상적)
SELECT TREND_RUN_SEQ, PERIOD_FILTER, FINAL_RANK, COUNT(*) AS cnt
FROM T_TREND_KEYWORD_FINAL_RANK
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER, FINAL_RANK
HAVING cnt > 1;

-- 3) 최종순위 + 키워드명 + 키워드 전체 기사수(TODAY/D7/D14, BASE_DATE 기준)
SELECT
  f.TREND_RUN_SEQ,
  f.PERIOD_FILTER,
  f.FINAL_RANK,
  f.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  COALESCE(a.article_cnt, 0) AS article_cnt_in_period
FROM T_TREND_KEYWORD_FINAL_RANK f
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = f.KEYWORD_SEQ
LEFT JOIN (
  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'TODAY' AS PERIOD_FILTER,
    COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'D7' AS PERIOD_FILTER,
    COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'D14' AS PERIOD_FILTER,
    COUNT(*) AS article_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ
) a
  ON a.TREND_RUN_SEQ = f.TREND_RUN_SEQ
 AND a.KEYWORD_SEQ   = f.KEYWORD_SEQ
 AND a.PERIOD_FILTER = f.PERIOD_FILTER
WHERE f.TREND_RUN_SEQ = @run_seq
ORDER BY f.PERIOD_FILTER, f.FINAL_RANK;

-- 4) 최종순위 + 키워드명 + 언론사별 TODAY/D7/D14 기사수(BASE_DATE 기준)
SELECT
  f.TREND_RUN_SEQ,
  f.PERIOD_FILTER,
  f.FINAL_RANK,
  f.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  a.MEDIA_CODE,
  m.MEDIA_NAME,
  CASE
    WHEN f.PERIOD_FILTER = 'TODAY' THEN COALESCE(a.today_cnt, 0)
    WHEN f.PERIOD_FILTER = 'D7'    THEN COALESCE(a.d7_cnt, 0)
    WHEN f.PERIOD_FILTER = 'D14'   THEN COALESCE(a.d14_cnt, 0)
    ELSE 0
  END AS article_cnt_in_period
FROM T_TREND_KEYWORD_FINAL_RANK f
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = f.KEYWORD_SEQ
LEFT JOIN (
  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    a.MEDIA_CODE,
    SUM(
      CASE
        WHEN a.PUBLISHED_AT IS NOT NULL
         AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
         AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
        THEN 1 ELSE 0
      END
    ) AS today_cnt,
    SUM(
      CASE
        WHEN a.PUBLISHED_AT IS NOT NULL
         AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
         AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
        THEN 1 ELSE 0
      END
    ) AS d7_cnt,
    SUM(
      CASE
        WHEN a.PUBLISHED_AT IS NOT NULL
         AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
         AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
        THEN 1 ELSE 0
      END
    ) AS d14_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE
) a
  ON a.TREND_RUN_SEQ = f.TREND_RUN_SEQ
 AND a.KEYWORD_SEQ   = f.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m
  ON m.MEDIA_CODE = a.MEDIA_CODE
WHERE f.TREND_RUN_SEQ = @run_seq
ORDER BY f.PERIOD_FILTER, f.FINAL_RANK, article_cnt_in_period DESC, a.MEDIA_CODE;

-- 5) FINAL_RANK의 ARTICLE_COUNT가 실제 기사 수(BASE_DATE 기준 TODAY/D7/D14)와 맞는지(0건 정상)
SELECT
  f.TREND_RUN_SEQ,
  f.PERIOD_FILTER,
  f.FINAL_RANK,
  f.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  f.ARTICLE_COUNT AS stored_cnt,
  COALESCE(a.real_cnt, 0) AS real_cnt
FROM T_TREND_KEYWORD_FINAL_RANK f
JOIN T_TREND_RUN r
  ON r.TREND_RUN_SEQ = f.TREND_RUN_SEQ
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = f.KEYWORD_SEQ
LEFT JOIN (
  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'TODAY' AS PERIOD_FILTER,
    COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r2 ON r2.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r2.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r2.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'D7' AS PERIOD_FILTER,
    COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r2 ON r2.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r2.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r2.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  SELECT
    a.TREND_RUN_SEQ,
    a.KEYWORD_SEQ,
    'D14' AS PERIOD_FILTER,
    COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r2 ON r2.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r2.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r2.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ
) a
  ON a.TREND_RUN_SEQ = f.TREND_RUN_SEQ
 AND a.KEYWORD_SEQ   = f.KEYWORD_SEQ
 AND a.PERIOD_FILTER = f.PERIOD_FILTER
WHERE f.TREND_RUN_SEQ = @run_seq
  AND COALESCE(a.real_cnt, 0) <> COALESCE(f.ARTICLE_COUNT, 0)
ORDER BY f.PERIOD_FILTER, f.FINAL_RANK
LIMIT 200;

-- 6) (추가) 스냅샷 키워드 대비 FINAL_RANK가 누락된 조합이 있는지(0건 정상)
-- 키워드마다 TODAY/D7/D14 모두 만들어야 한다는 전제라면, 누락을 빠르게 찾을 수 있음
WITH periods AS (
  SELECT 'TODAY' AS PERIOD_FILTER
  UNION ALL SELECT 'D7'
  UNION ALL SELECT 'D14'
)
SELECT
  s.TREND_RUN_SEQ,
  s.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  p.PERIOD_FILTER
FROM T_TREND_KEYWORD_SNAPSHOT s
JOIN T_TREND_KEYWORD_MASTER km
  ON km.KEYWORD_SEQ = s.KEYWORD_SEQ
CROSS JOIN periods p
LEFT JOIN T_TREND_KEYWORD_FINAL_RANK f
  ON f.TREND_RUN_SEQ = s.TREND_RUN_SEQ
 AND f.KEYWORD_SEQ   = s.KEYWORD_SEQ
 AND f.PERIOD_FILTER = p.PERIOD_FILTER
WHERE s.TREND_RUN_SEQ = @run_seq
  AND f.FINAL_RANK_SEQ IS NULL
GROUP BY s.TREND_RUN_SEQ, s.KEYWORD_SEQ, km.KEYWORD_NAME, p.PERIOD_FILTER
ORDER BY p.PERIOD_FILTER, s.KEYWORD_SEQ;


/* ----------------------------------------------------------------------
  8) T_ANALYZE_MEDIA_STAT (기사량 통계)
------------------------------------------------------------------------ */

-- 1) run/period 기준 통계 행 수
-- 0건이 안나와도 정상
-- rows_count = 키워드 25개 × (매체 9개 + 전체 1개) = 250
-- zero_rows_count = 그 중에서 ARTICLE_COUNT=0인 행 개수 => 이 1개의 의미는 특정 키워드의 특정 매체에서 발행한 기사가 0개라는 뜻
-- min_article_cnt / max_article_cnt : 그 period에서 조합별 기사수 최소/최대
-- sum_article_cnt : 모든 조합의 ARTICLE_COUNT 합 => 전체 포함이라 중복 합임
SELECT
  TREND_RUN_SEQ,
  PERIOD_FILTER,
  SUM(ARTICLE_COUNT) AS sum_article_cnt,
  MIN(ARTICLE_COUNT) AS min_article_cnt,
  MAX(ARTICLE_COUNT) AS max_article_cnt,
  SUM(CASE WHEN ARTICLE_COUNT = 0 THEN 1 ELSE 0 END) AS zero_rows_cnt,
  COUNT(*) AS rows_cnt
FROM T_ANALYZE_MEDIA_STAT
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER;

-- 2) 통계값(ARTICLE_COUNT)이 실제 기사 수(BASE_DATE 기준 TODAY/D7/D14)와 맞는지(불일치: 0건 정상)
SELECT
  s.TREND_RUN_SEQ, s.KEYWORD_SEQ, s.MEDIA_CODE, s.PERIOD_FILTER,
  s.ARTICLE_COUNT AS stored_cnt,
  COALESCE(a.real_cnt, 0) AS real_cnt
FROM T_ANALYZE_MEDIA_STAT s
LEFT JOIN (
  -- TODAY: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'TODAY' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- TODAY: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'TODAY' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE

  UNION ALL

  -- D7: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'D7' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- D7: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'D7' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE

  UNION ALL

  -- D14: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'D14' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- D14: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'D14' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE
) a
  ON a.TREND_RUN_SEQ  = s.TREND_RUN_SEQ
 AND a.KEYWORD_SEQ    = s.KEYWORD_SEQ
 AND a.MEDIA_CODE     = s.MEDIA_CODE
 AND a.PERIOD_FILTER  = s.PERIOD_FILTER
WHERE s.TREND_RUN_SEQ = @run_seq
  AND s.PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND s.ARTICLE_COUNT <> COALESCE(a.real_cnt, 0)
ORDER BY ABS(s.ARTICLE_COUNT - COALESCE(a.real_cnt, 0)) DESC
LIMIT 200;

-- 3) 중복(0건 정상: UNIQUE)
SELECT TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER, COUNT(*) AS cnt
FROM T_ANALYZE_MEDIA_STAT
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER
HAVING cnt > 1;

-- 4) (추가) 실제 기사(기간/매체/키워드) 조합이 있는데 MEDIA_STAT 행이 아예 없는지(0건 정상)
-- 불일치(값 차이)가 아니라 "행 자체 누락"을 잡아내는 용도
-- 예를들어 run 12의 키워드 74에 대해 D14 기간 동안 기사(전체 언론사 기준)가 실제로 21건 있는데,
-- T_ANALYZE_MEDIA_STAT에는 (12, 74, MEDIA_CODE=0, D14) 행이 없다.
SELECT
  e.TREND_RUN_SEQ, e.KEYWORD_SEQ, e.MEDIA_CODE, e.PERIOD_FILTER,
  e.real_cnt
FROM (
  -- TODAY: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'TODAY' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- TODAY: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'TODAY' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(r.BASE_DATE)
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE

  UNION ALL

  -- D7: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'D7' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- D7: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'D7' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 6 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE

  UNION ALL

  -- D14: 전체(0)
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, 0 AS MEDIA_CODE, 'D14' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ

  UNION ALL

  -- D14: 매체별
  SELECT
    a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE, 'D14' AS PERIOD_FILTER, COUNT(*) AS real_cnt
  FROM T_NEWS_ARTICLE a
  JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = a.TREND_RUN_SEQ
  WHERE a.TREND_RUN_SEQ = @run_seq
    AND a.PUBLISHED_AT IS NOT NULL
    AND a.PUBLISHED_AT >= TIMESTAMP(DATE_SUB(r.BASE_DATE, INTERVAL 13 DAY))
    AND a.PUBLISHED_AT <  TIMESTAMP(DATE_ADD(r.BASE_DATE, INTERVAL 1 DAY))
  GROUP BY a.TREND_RUN_SEQ, a.KEYWORD_SEQ, a.MEDIA_CODE
) e
LEFT JOIN T_ANALYZE_MEDIA_STAT s
  ON s.TREND_RUN_SEQ = e.TREND_RUN_SEQ
 AND s.KEYWORD_SEQ   = e.KEYWORD_SEQ
 AND s.MEDIA_CODE    = e.MEDIA_CODE
 AND s.PERIOD_FILTER = e.PERIOD_FILTER
WHERE e.TREND_RUN_SEQ = @run_seq
  AND s.STAT_SEQ IS NULL
ORDER BY e.PERIOD_FILTER, e.KEYWORD_SEQ, e.MEDIA_CODE
LIMIT 200;


/* ----------------------------------------------------------------------
  9) T_ANALYZE_AI_SUMMARY + T_ANALYZE_AI_SUMMARY_ARTICLE (AI 요약)
------------------------------------------------------------------------ */

-- 1) run 기준 요약 존재 여부/개수
SELECT TREND_RUN_SEQ, COUNT(*) AS summary_cnt
FROM T_ANALYZE_AI_SUMMARY
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ;

-- 2) 키워드당 1개인지(0건 정상: UNIQUE(RUN,KEYWORD))
SELECT TREND_RUN_SEQ, KEYWORD_SEQ, COUNT(*) AS cnt
FROM T_ANALYZE_AI_SUMMARY
WHERE TREND_RUN_SEQ = @run_seq
GROUP BY TREND_RUN_SEQ, KEYWORD_SEQ
HAVING cnt > 1;

-- 3) 요약 텍스트 비어있는지(0건 정상)
SELECT SUMMARY_SEQ, KEYWORD_SEQ
FROM T_ANALYZE_AI_SUMMARY
WHERE TREND_RUN_SEQ = @run_seq
  AND (SUMMARY_TEXT IS NULL OR TRIM(SUMMARY_TEXT) = '');

-- 4) 요약-기사 매핑: 요약별 사용 기사 수
SELECT a.SUMMARY_SEQ, a.KEYWORD_SEQ, COUNT(l.LINK_SEQ) AS used_articles
FROM T_ANALYZE_AI_SUMMARY a
LEFT JOIN T_ANALYZE_AI_SUMMARY_ARTICLE l ON l.SUMMARY_SEQ = a.SUMMARY_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq
GROUP BY a.SUMMARY_SEQ, a.KEYWORD_SEQ
ORDER BY used_articles DESC;

-- 5) 매핑의 고아(원칙상 0건)
SELECT l.LINK_SEQ
FROM T_ANALYZE_AI_SUMMARY_ARTICLE l
LEFT JOIN T_ANALYZE_AI_SUMMARY s ON s.SUMMARY_SEQ = l.SUMMARY_SEQ
LEFT JOIN T_NEWS_ARTICLE a ON a.ARTICLE_SEQ = l.ARTICLE_SEQ
WHERE s.SUMMARY_SEQ IS NULL OR a.ARTICLE_SEQ IS NULL
LIMIT 200;

-- 6) 매핑의 입력 순서 중복(0건 정상: UNIQUE)
SELECT SUMMARY_SEQ, INPUT_ORDER, COUNT(*) AS cnt
FROM T_ANALYZE_AI_SUMMARY_ARTICLE
GROUP BY SUMMARY_SEQ, INPUT_ORDER
HAVING cnt > 1;


/* ----------------------------------------------------------------------
  10) T_ANALYZE_SENTIMENT (감성 분석)
------------------------------------------------------------------------ */

-- 1) run/period 기준 감성 행 수(전체/매체별)
-- 예를들어 D14 / MEDIA_CODE=0 / rows_cnt=13 => D14 기간에서 “전체(0)” 집계 감성 결과가 13개 키워드에 대해서만 저장돼 있다는 뜻
-- 예를들어 D14 / MEDIA_CODE=1023 / rows_cnt=11 => D14에서 조선일보(1023) 감성 결과가 11개 키워드만 저장됨
SELECT TREND_RUN_SEQ, PERIOD_FILTER, MEDIA_CODE, COUNT(*) AS rows_cnt
FROM T_ANALYZE_SENTIMENT
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER, MEDIA_CODE
ORDER BY PERIOD_FILTER, MEDIA_CODE;

-- 2) 제목 비율 합이 100 근처인지(라운딩 허용 오차 0.5)
-- (개선) 제목이 "미계산 상태(0,0,0)"로 저장되는 정책이 있을 수 있으므로,
--        합이 0인 행은 검사에서 제외한다.
-- 0건 정상
SELECT SENTIMENT_SEQ, TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER,
       (POSITIVE_PCT_TITLE + NEUTRAL_PCT_TITLE + NEGATIVE_PCT_TITLE) AS sum_title
FROM T_ANALYZE_SENTIMENT
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND (POSITIVE_PCT_TITLE + NEUTRAL_PCT_TITLE + NEGATIVE_PCT_TITLE) > 0
  AND ABS((POSITIVE_PCT_TITLE + NEUTRAL_PCT_TITLE + NEGATIVE_PCT_TITLE) - 100) > 0.5
ORDER BY ABS((POSITIVE_PCT_TITLE + NEUTRAL_PCT_TITLE + NEGATIVE_PCT_TITLE) - 100) DESC
LIMIT 200;

-- 3) 본문 비율 합이 100 근처인지(본문 미계산이면 0일 수 있음)
-- 0건 정상
SELECT SENTIMENT_SEQ, TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER,
       (POSITIVE_PCT_CONTENT + NEUTRAL_PCT_CONTENT + NEGATIVE_PCT_CONTENT) AS sum_content
FROM T_ANALYZE_SENTIMENT
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND (POSITIVE_PCT_CONTENT + NEUTRAL_PCT_CONTENT + NEGATIVE_PCT_CONTENT) > 0
  AND ABS((POSITIVE_PCT_CONTENT + NEUTRAL_PCT_CONTENT + NEGATIVE_PCT_CONTENT) - 100) > 0.5
ORDER BY ABS((POSITIVE_PCT_CONTENT + NEUTRAL_PCT_CONTENT + NEGATIVE_PCT_CONTENT) - 100) DESC
LIMIT 200;

-- 4) 값 범위(0~100) 밖(0건 정상)
SELECT SENTIMENT_SEQ
FROM T_ANALYZE_SENTIMENT
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND (
    POSITIVE_PCT_TITLE   NOT BETWEEN 0 AND 100 OR
    NEUTRAL_PCT_TITLE    NOT BETWEEN 0 AND 100 OR
    NEGATIVE_PCT_TITLE   NOT BETWEEN 0 AND 100 OR
    POSITIVE_PCT_CONTENT NOT BETWEEN 0 AND 100 OR
    NEUTRAL_PCT_CONTENT  NOT BETWEEN 0 AND 100 OR
    NEGATIVE_PCT_CONTENT NOT BETWEEN 0 AND 100
  )
LIMIT 200;


/* ----------------------------------------------------------------------
  11) T_ANALYZE_MEDIA_BIAS (편향도)
------------------------------------------------------------------------ */

-- 1) run/period 기준 편향 행 수
-- run 12에 대해 TODAY 기간에서 편향도 결과가 저장된 조합이 31개, D7은 63개, D14는 74개
SELECT TREND_RUN_SEQ, PERIOD_FILTER, COUNT(*) AS rows_cnt
FROM T_ANALYZE_MEDIA_BIAS
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER;

-- 2) 값 범위(-10 ~ +10) 밖 확인(0건 정상)
SELECT BIAS_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER,
       BIAS_SCORE_TITLE, BIAS_SCORE_CONTENT
FROM T_ANALYZE_MEDIA_BIAS
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND (
       (BIAS_SCORE_TITLE   IS NOT NULL AND (BIAS_SCORE_TITLE   < -10 OR BIAS_SCORE_TITLE   > 10))
    OR (BIAS_SCORE_CONTENT IS NOT NULL AND (BIAS_SCORE_CONTENT < -10 OR BIAS_SCORE_CONTENT > 10))
  )
LIMIT 200;


-- 3) 감성 테이블과 조합이 맞는지(감성이 있는데 편향이 없다)
-- 전체에 대한 편향도는 없는것이 정상
SELECT
  s.KEYWORD_SEQ, s.MEDIA_CODE, s.PERIOD_FILTER
FROM T_ANALYZE_SENTIMENT s
LEFT JOIN T_ANALYZE_MEDIA_BIAS b
  ON b.TREND_RUN_SEQ = s.TREND_RUN_SEQ
 AND b.KEYWORD_SEQ = s.KEYWORD_SEQ
 AND b.MEDIA_CODE = s.MEDIA_CODE
 AND b.PERIOD_FILTER = s.PERIOD_FILTER
WHERE s.TREND_RUN_SEQ = @run_seq
  AND s.PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND b.BIAS_SEQ IS NULL
LIMIT 200;


/* ----------------------------------------------------------------------
  12) T_ANALYZE_WORDCLOUD + ITEM (워드클라우드)
------------------------------------------------------------------------ */

-- 1) 헤더 개수
SELECT TREND_RUN_SEQ, PERIOD_FILTER, WC_TYPE, COUNT(*) AS wc_headers
FROM T_ANALYZE_WORDCLOUD
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER, WC_TYPE;

-- 2) 헤더별 아이템 개수(상위)
-- wc_headers가 키워드 개수 만큼 나오면 정상
SELECT w.WC_SEQ, w.KEYWORD_SEQ, w.MEDIA_CODE, w.PERIOD_FILTER, w.WC_TYPE,
       COUNT(i.WC_ITEM_SEQ) AS item_cnt
FROM T_ANALYZE_WORDCLOUD w
LEFT JOIN T_ANALYZE_WORDCLOUD_ITEM i ON i.WC_SEQ = w.WC_SEQ
WHERE w.TREND_RUN_SEQ = @run_seq
  AND w.PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
GROUP BY w.WC_SEQ, w.KEYWORD_SEQ, w.MEDIA_CODE, w.PERIOD_FILTER, w.WC_TYPE
ORDER BY item_cnt DESC
LIMIT 200;

-- 3) 아이템 랭크 중복(0건 정상: UNIQUE)
SELECT WC_SEQ, RANK_NO, COUNT(*) AS cnt
FROM T_ANALYZE_WORDCLOUD_ITEM
GROUP BY WC_SEQ, RANK_NO
HAVING cnt > 1;

-- 4) WEIGHT 음수/이상치(0건 정상)
SELECT WC_ITEM_SEQ, WC_SEQ, WORD_TEXT, WEIGHT
FROM T_ANALYZE_WORDCLOUD_ITEM
WHERE WEIGHT < 0
LIMIT 200;

-- 5) 고아 아이템(0건 정상: FK)
SELECT i.WC_ITEM_SEQ
FROM T_ANALYZE_WORDCLOUD_ITEM i
LEFT JOIN T_ANALYZE_WORDCLOUD w ON w.WC_SEQ = i.WC_SEQ
WHERE w.WC_SEQ IS NULL
LIMIT 200;


/* ----------------------------------------------------------------------
  13) T_ANALYZE_CO_MENTION_GRAPH / NODE / EDGE (공동언급 그래프)
------------------------------------------------------------------------ */

-- 1) 그래프 헤더 존재/개수
SELECT TREND_RUN_SEQ, PERIOD_FILTER,
       COUNT(*) AS graph_cnt,
       SUM(NODE_COUNT) AS sum_node_count,
       SUM(EDGE_COUNT) AS sum_edge_count
FROM T_ANALYZE_CO_MENTION_GRAPH
WHERE TREND_RUN_SEQ = @run_seq
  AND PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
GROUP BY TREND_RUN_SEQ, PERIOD_FILTER;

-- 2) 헤더의 NODE_COUNT/EDGE_COUNT가 실제와 맞는지(불일치: 0건 정상)
SELECT
  g.GRAPH_SEQ,
  g.NODE_COUNT, COALESCE(n.real_nodes, 0) AS real_nodes,
  g.EDGE_COUNT, COALESCE(e.real_edges, 0) AS real_edges
FROM T_ANALYZE_CO_MENTION_GRAPH g
LEFT JOIN (
  SELECT GRAPH_SEQ, COUNT(*) AS real_nodes
  FROM T_ANALYZE_CO_MENTION_NODE
  GROUP BY GRAPH_SEQ
) n ON n.GRAPH_SEQ = g.GRAPH_SEQ
LEFT JOIN (
  SELECT GRAPH_SEQ, COUNT(*) AS real_edges
  FROM T_ANALYZE_CO_MENTION_EDGE
  GROUP BY GRAPH_SEQ
) e ON e.GRAPH_SEQ = g.GRAPH_SEQ
WHERE g.TREND_RUN_SEQ = @run_seq
  AND g.PERIOD_FILTER IN ('TODAY', 'D7', 'D14')
  AND (g.NODE_COUNT <> COALESCE(n.real_nodes, 0) OR g.EDGE_COUNT <> COALESCE(e.real_edges, 0))
ORDER BY g.GRAPH_SEQ DESC
LIMIT 200;

-- 3) EDGE가 참조하는 NODE가 실제로 존재하는지(0건 정상)
SELECT e.EDGE_SEQ
FROM T_ANALYZE_CO_MENTION_EDGE e
LEFT JOIN T_ANALYZE_CO_MENTION_NODE n1 ON n1.NODE_SEQ = e.FROM_NODE_SEQ
LEFT JOIN T_ANALYZE_CO_MENTION_NODE n2 ON n2.NODE_SEQ = e.TO_NODE_SEQ
WHERE n1.NODE_SEQ IS NULL OR n2.NODE_SEQ IS NULL
LIMIT 200;

-- 4) 동일 GRAPH 내 동일 엔티티 중복(0건 정상: UNIQUE)
SELECT GRAPH_SEQ, ENTITY_NAME, COUNT(*) AS cnt
FROM T_ANALYZE_CO_MENTION_NODE
GROUP BY GRAPH_SEQ, ENTITY_NAME
HAVING cnt > 1;

-- 5) 동일 GRAPH 내 동일 FROM-TO 중복(0건 정상: UNIQUE)
SELECT GRAPH_SEQ, FROM_NODE_SEQ, TO_NODE_SEQ, COUNT(*) AS cnt
FROM T_ANALYZE_CO_MENTION_EDGE
GROUP BY GRAPH_SEQ, FROM_NODE_SEQ, TO_NODE_SEQ
HAVING cnt > 1;


/* ----------------------------------------------------------------------
  14) 파이프라인 단계별 "최소 1행 존재" 빠른 체크(요약)
------------------------------------------------------------------------ */

SELECT 'T_TREND_KEYWORD_SNAPSHOT' AS tbl, COUNT(*) AS cnt
FROM T_TREND_KEYWORD_SNAPSHOT WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_NEWS_ARTICLE', COUNT(*)
FROM T_NEWS_ARTICLE WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
-- 댓글은 기사(run)에 종속되므로 run 기준으로 카운트(전체 댓글 카운트가 아니라 run별 체크)
SELECT 'T_NEWS_COMMENT', COUNT(*)
FROM T_NEWS_COMMENT c
JOIN T_NEWS_ARTICLE a ON a.ARTICLE_SEQ = c.ARTICLE_SEQ
WHERE a.TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_TREND_KEYWORD_FINAL_RANK', COUNT(*)
FROM T_TREND_KEYWORD_FINAL_RANK WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_MEDIA_STAT', COUNT(*)
FROM T_ANALYZE_MEDIA_STAT WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_AI_SUMMARY', COUNT(*)
FROM T_ANALYZE_AI_SUMMARY WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_SENTIMENT', COUNT(*)
FROM T_ANALYZE_SENTIMENT WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_MEDIA_BIAS', COUNT(*)
FROM T_ANALYZE_MEDIA_BIAS WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_WORDCLOUD', COUNT(*)
FROM T_ANALYZE_WORDCLOUD WHERE TREND_RUN_SEQ = @run_seq

UNION ALL
SELECT 'T_ANALYZE_CO_MENTION_GRAPH', COUNT(*)
FROM T_ANALYZE_CO_MENTION_GRAPH WHERE TREND_RUN_SEQ = @run_seq;


/* ----------------------------------------------------------------------
  15) (추가) 분석 테이블 FK 무결성 빠른 체크(원칙상 0건)
  - FK가 걸려 있어도 과거 데이터/마이그레이션/수동 적재 과정에서 깨질 수 있으므로,
    "이번 run" 기준으로 고아키를 빠르게 확인한다.
------------------------------------------------------------------------ */

-- 1) MEDIA_STAT FK 무결성(원칙상 0건)
SELECT s.STAT_SEQ, s.TREND_RUN_SEQ, s.KEYWORD_SEQ, s.MEDIA_CODE
FROM T_ANALYZE_MEDIA_STAT s
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = s.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = s.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = s.MEDIA_CODE
WHERE s.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL OR m.MEDIA_CODE IS NULL)
LIMIT 200;

-- 2) SENTIMENT FK 무결성(원칙상 0건)
SELECT s.SENTIMENT_SEQ, s.TREND_RUN_SEQ, s.KEYWORD_SEQ, s.MEDIA_CODE
FROM T_ANALYZE_SENTIMENT s
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = s.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = s.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = s.MEDIA_CODE
WHERE s.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL OR m.MEDIA_CODE IS NULL)
LIMIT 200;

-- 3) MEDIA_BIAS FK 무결성(원칙상 0건)
SELECT b.BIAS_SEQ, b.TREND_RUN_SEQ, b.KEYWORD_SEQ, b.MEDIA_CODE
FROM T_ANALYZE_MEDIA_BIAS b
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = b.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = b.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = b.MEDIA_CODE
WHERE b.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL OR m.MEDIA_CODE IS NULL)
LIMIT 200;

-- 4) WORDCLOUD 헤더 FK 무결성(원칙상 0건)
SELECT w.WC_SEQ, w.TREND_RUN_SEQ, w.KEYWORD_SEQ, w.MEDIA_CODE
FROM T_ANALYZE_WORDCLOUD w
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = w.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = w.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = w.MEDIA_CODE
WHERE w.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL OR m.MEDIA_CODE IS NULL)
LIMIT 200;

-- 5) AI_SUMMARY FK 무결성(원칙상 0건)
SELECT s.SUMMARY_SEQ, s.TREND_RUN_SEQ, s.KEYWORD_SEQ
FROM T_ANALYZE_AI_SUMMARY s
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = s.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = s.KEYWORD_SEQ
WHERE s.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL)
LIMIT 200;

-- 6) CO_MENTION_GRAPH FK 무결성(원칙상 0건)
SELECT g.GRAPH_SEQ, g.TREND_RUN_SEQ, g.KEYWORD_SEQ, g.MEDIA_CODE
FROM T_ANALYZE_CO_MENTION_GRAPH g
LEFT JOIN T_TREND_RUN r ON r.TREND_RUN_SEQ = g.TREND_RUN_SEQ
LEFT JOIN T_TREND_KEYWORD_MASTER k ON k.KEYWORD_SEQ = g.KEYWORD_SEQ
LEFT JOIN T_NEWS_MEDIA m ON m.MEDIA_CODE = g.MEDIA_CODE
WHERE g.TREND_RUN_SEQ = @run_seq
  AND (r.TREND_RUN_SEQ IS NULL OR k.KEYWORD_SEQ IS NULL OR m.MEDIA_CODE IS NULL)
LIMIT 200;

-- 7) CO_MENTION_NODE -> GRAPH 고아(원칙상 0건)
SELECT n.NODE_SEQ, n.GRAPH_SEQ
FROM T_ANALYZE_CO_MENTION_NODE n
LEFT JOIN T_ANALYZE_CO_MENTION_GRAPH g ON g.GRAPH_SEQ = n.GRAPH_SEQ
WHERE g.GRAPH_SEQ IS NULL
LIMIT 200;

-- 8) CO_MENTION_EDGE -> GRAPH 고아(원칙상 0건)
SELECT e.EDGE_SEQ, e.GRAPH_SEQ
FROM T_ANALYZE_CO_MENTION_EDGE e
LEFT JOIN T_ANALYZE_CO_MENTION_GRAPH g ON g.GRAPH_SEQ = e.GRAPH_SEQ
WHERE g.GRAPH_SEQ IS NULL
LIMIT 200;


/* ----------------------------------------------------------------------
  16) (추가) "기대 조합 누락" 빠른 체크(정책에 따라 0건이 정상)
  - 여기서의 "기대"는 파이프라인 정책에 따라 달라질 수 있다.
  - 예) D14 분석을 아예 돌리지 않는다면, D14 누락은 정상이다.
------------------------------------------------------------------------ */

-- 1) 스냅샷 키워드 대비 AI 요약 누락(키워드당 요약 1개 정책이면 0건 정상)
SELECT
  s.KEYWORD_SEQ,
  km.KEYWORD_NAME
FROM T_TREND_KEYWORD_SNAPSHOT s
JOIN T_TREND_KEYWORD_MASTER km ON km.KEYWORD_SEQ = s.KEYWORD_SEQ
LEFT JOIN T_ANALYZE_AI_SUMMARY a
  ON a.TREND_RUN_SEQ = s.TREND_RUN_SEQ
 AND a.KEYWORD_SEQ = s.KEYWORD_SEQ
WHERE s.TREND_RUN_SEQ = @run_seq
  AND a.SUMMARY_SEQ IS NULL
GROUP BY s.KEYWORD_SEQ, km.KEYWORD_NAME
ORDER BY s.KEYWORD_SEQ;

-- 2) 스냅샷 키워드 대비 MEDIA_STAT(전체=MEDIA_CODE 0) 누락(키워드/기간별 전체 행이 있어야 한다면 0건 정상)
WITH periods2 AS (
  SELECT 'TODAY' AS PERIOD_FILTER
  UNION ALL SELECT 'D7'
  UNION ALL SELECT 'D14'
)
SELECT
  s.KEYWORD_SEQ,
  km.KEYWORD_NAME,
  p.PERIOD_FILTER
FROM T_TREND_KEYWORD_SNAPSHOT s
JOIN T_TREND_KEYWORD_MASTER km ON km.KEYWORD_SEQ = s.KEYWORD_SEQ
CROSS JOIN periods2 p
LEFT JOIN T_ANALYZE_MEDIA_STAT st
  ON st.TREND_RUN_SEQ = s.TREND_RUN_SEQ
 AND st.KEYWORD_SEQ = s.KEYWORD_SEQ
 AND st.MEDIA_CODE = 0
 AND st.PERIOD_FILTER = p.PERIOD_FILTER
WHERE s.TREND_RUN_SEQ = @run_seq
  AND st.STAT_SEQ IS NULL
GROUP BY s.KEYWORD_SEQ, km.KEYWORD_NAME, p.PERIOD_FILTER
ORDER BY p.PERIOD_FILTER, s.KEYWORD_SEQ;