-- data-pipeline/db/schema.sql
-- 테이블을 만드는 스키마(DDL)
-- 이 문서를 통해 테이블을 생성하면 해당 파일을 삭제해도 DB는 남아있기 때문에 그대로 돌아가지만 추후 스키마를 수정할 수도 있으므로 삭제해서는 안된다.
-- MySQL 8.x / utf8mb4 기준

-- 문자 인코딩을 utf8mb4로 쓰겠다는 뜻
SET NAMES utf8mb4;

-- 시간대(타임존)를 한국으로 맞춤
SET time_zone = '+09:00';


-- FK 때문에 생성 순서 중요 (T_NEWS_MEDIA -> T_TREND_KEYWORD_MASTER -> T_NEWS_ARTICLE -> ...)
-- 실제 실행(적용) 순서: DDL을 작성한 순서
-- 1. 뉴스 관련 데이터 저장 테이블 모음
-- (1)-1 언론사(T_NEWS_MEDIA) 테이블 생성
CREATE TABLE IF NOT EXISTS T_NEWS_MEDIA (    -- IF NOT EXISTS: 이 테이블이 이미 있으면 만들지 말고 그냥 넘어가라는 뜻
  MEDIA_CODE INT NOT NULL,
  MEDIA_NAME VARCHAR(50) NOT NULL,

  -- PK: 언론사 코드
  PRIMARY KEY (MEDIA_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;  -- 이 테이블의 기본 설정을 정하는 옵션


-- (1)-2 T_NEWS_MEDIA 생성 직후: T_NEWS_MEDIA 테이블에 초기 언론사 코드 데이터(Seed) 넣는 SQL(DML)
-- INSERT ... ON DUPLICATE KEY UPDATE: PK/UNIQUE 키 충돌이 없으면 INSERT하고, PK/UNIQUE 키 충돌이 나면 행을 수정함(UPDATE) => 업서트(UPSERT = INSERT + UPDATE)
INSERT INTO T_NEWS_MEDIA (MEDIA_CODE, MEDIA_NAME) VALUES
(0, '전체'),
(1023, '조선일보'),
(1025, '중앙일보'),
(1020, '동아일보'),
(1028, '한겨레'),
(1032, '경향신문'),
(1002, '프레시안'),
(1469, '한국일보'),
(1081, '서울신문'),
(1001, '연합뉴스')
ON DUPLICATE KEY UPDATE MEDIA_NAME = VALUES(MEDIA_NAME);


-- (2)-1 트렌드 키워드 사전(마스터) (T_TREND_KEYWORD_MASTER) 테이블 생성
-- MySQL에선 BOOLEAN 대신 TINYINT(1)을 사용
CREATE TABLE IF NOT EXISTS T_TREND_KEYWORD_MASTER (
  KEYWORD_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  KEYWORD_NAME VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 

  -- PK: 키워드 일련번호
  PRIMARY KEY (KEYWORD_SEQ),

  -- 키워드 명 유니크 제약
  UNIQUE KEY UK_T_TREND_KEYWORD_MASTER__NAME (KEYWORD_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (2)-2 트렌드 수집(T_TREND_RUN) 테이블 생성
-- 트렌드 run은 최신 N개만 유지(retention.py로 구현 예정)
-- TREND_RUN_SEQ(run)을 삭제하면, 해당 run의 스냅샷(T_TREND_KEYWORD_SNAPSHOT)도 CASCADE로 함께 삭제됨
-- 또한 run 삭제를 기준으로 연결된 뉴스 기사/댓글/분석 결과도 함께 정리되도록 설계됨
CREATE TABLE IF NOT EXISTS T_TREND_RUN (
  TREND_RUN_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  BASE_DATE DATE NOT NULL,
  RUN_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TOP_N INT NULL DEFAULT NULL,

  -- PK: 트랜드 실행 일련번호
  PRIMARY KEY (TREND_RUN_SEQ),

  -- 조회 성능용 인덱스
  -- 이 코드를 적어두면 나중에 스프링 부트가 JPA/SQL로 DB 조회/정렬/필터링할 때 DB가 더 빨리 찾을 수 있게됨
  -- 여기 KEY 인덱스명 (컬럼...)에서 인덱스명은 사용자가 정함
  KEY IX_T_TREND_RUN__BASE_DATE (BASE_DATE),
  KEY IX_T_TREND_RUN__RUN_AT (RUN_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- (2)-3 트렌드 키워드 스냅샷(T_TREND_KEYWORD_SNAPSHOT) 테이블 생성
-- 이곳에서의 TREND_RANK는 실검 순위. 추후 기사 수를 기반으로한 최종 순위는 T_TREND_KEYWORD_FINAL_RANK에서 집계예정
CREATE TABLE IF NOT EXISTS T_TREND_KEYWORD_SNAPSHOT (
  TREND_ITEM_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  TREND_RANK INT NOT NULL,  

  -- PK: 트렌드 항목 일련번호 
  PRIMARY KEY (TREND_ITEM_SEQ),

  -- 중복 방지
  -- 예를들어 TREND_RUN_SEQ=15에서 TREND_RANK=1은 오직 한 행만
  UNIQUE KEY UK_T_TREND_KEYWORD_SNAPSHOT__RUN_RANK (TREND_RUN_SEQ, TREND_RANK),

  -- 예를들어 TREND_RUN_SEQ=15에서 KEYWORD_SEQ=300 키워드는 오직 한 행만
  UNIQUE KEY UK_T_TREND_KEYWORD_SNAPSHOT__RUN_KEYWORD (TREND_RUN_SEQ, KEYWORD_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_TREND_KEYWORD_SNAPSHOT__RUN (TREND_RUN_SEQ),
  KEY IX_T_TREND_KEYWORD_SNAPSHOT__KEYWORD (KEYWORD_SEQ),

  -- FK: 트렌드 실행 일련번호
  -- ON UPDATE RESTRICT: 부모 테이블(T_TREND_RUN)의 TREND_RUN_SEQ 값을 수정(변경) 하는 걸 막음
  -- ON DELETE CASCADE: 어떤 트렌드 실행(run)을 삭제하면, 그 run에 딸린 스냅샷(T_TREND_KEYWORD_SNAPSHOT 행들)도 자동으로 같이 삭제됨
  -- 뉴스 기사/댓글/분석 결과 또한 스냅샷과 마찬가지로 run 삭제를 기준으로 함께 삭제되도록 정리되도록(CASCADE) 설계할 예정
  CONSTRAINT FK_T_TREND_KEYWORD_SNAPSHOT__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  -- ON UPDATE RESTRICT: T_TREND_KEYWORD_MASTER의 PK를 바꾸는 걸 막음(일반적으로 PK 변경 안 함)
  -- ON DELETE RESTRICT: 어떤 키워드를 T_TREND_KEYWORD_SNAPSHOT가 참조 중이면, 그 키워드를 T_TREND_KEYWORD_MASTER에서 삭제 못 하게 막음.
  CONSTRAINT FK_T_TREND_KEYWORD_SNAPSHOT__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (3) 뉴스기사(T_NEWS_ARTICLE) 테이블 생성
CREATE TABLE IF NOT EXISTS T_NEWS_ARTICLE (
  ARTICLE_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  SOURCE_URL VARCHAR(2048) NOT NULL,
  URL_HASH CHAR(64) NOT NULL,
  TITLE VARCHAR(300) NOT NULL,
  PUBLISHED_AT DATETIME NULL,
  CONTENT_TEXT MEDIUMTEXT NULL,
  MEDIA_CODE INT NOT NULL,
  TITLE_CLEAN VARCHAR(300) NULL,
  CONTENT_CLEAN MEDIUMTEXT NULL,
  PREPROCESSED_AT DATETIME NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  TREND_RUN_SEQ BIGINT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 

  -- PK: 뉴스글 일련번호
  PRIMARY KEY (ARTICLE_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_NEWS_ARTICLE__MEDIA_CODE (MEDIA_CODE),
  KEY IX_T_NEWS_ARTICLE__PUBLISHED_AT (PUBLISHED_AT),
  KEY IX_T_NEWS_ARTICLE__KEYWORD_SEQ (KEYWORD_SEQ),
  KEY IX_T_NEWS_ARTICLE__TREND_RUN_SEQ (TREND_RUN_SEQ),
  KEY IX_T_NEWS_ARTICLE__RUN_KEYWORD_PUB (TREND_RUN_SEQ, KEYWORD_SEQ, PUBLISHED_AT),

  -- 같은 키워드 안에서 같은 기사 중복만 방지
  -- TREND_RUN_SEQ, KEYWORD_SEQ, URL_HASH 세개의 조합이 모두 같으면 저장 불가능
  -- 같은 트렌드 실행에서 같은 키워드 인데도 URL 해시 값이 같다면 추가 저장 X
  UNIQUE KEY UK_T_NEWS_ARTICLE__RUN_KEYWORD_URLHASH (TREND_RUN_SEQ, KEYWORD_SEQ, URL_HASH),

  -- FK: 언론사 코드
  -- 기사에 저장되는 MEDIA_CODE는 반드시 T_NEWS_MEDIA에 존재하는 값이어야 함
  -- T_NEWS_MEDIA에서 사용 중인 언론사 코드는 삭제/변경할 수 없도록 막아 참조 무결성을 유지함
  CONSTRAINT FK_T_NEWS_ARTICLE__MEDIA 
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_NEWS_ARTICLE__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 트렌드 실행 일련번호 
  -- ON DELETE CASCADE: 여기서도 트렌드 스냅샷과 마찬가지로 TREND_RUN_SEQ가 삭제되면 해당 SEQ에 연결된 뉴스 기사도 삭제됨
  CONSTRAINT FK_T_NEWS_ARTICLE__TREND_RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (4) 뉴스 댓글(T_NEWS_COMMENT) 테이블 생성
CREATE TABLE IF NOT EXISTS T_NEWS_COMMENT (
  COMMENT_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  ARTICLE_SEQ BIGINT NOT NULL,
  COMMENT_HASH CHAR(64) NOT NULL,
  COMMENT_TEXT TEXT NOT NULL,
  COMMENT_CLEAN TEXT NULL,
  PREPROCESSED_AT DATETIME NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 

  -- PK: 댓글 일련번호
  PRIMARY KEY (COMMENT_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_NEWS_COMMENT__ARTICLE_SEQ (ARTICLE_SEQ),

  -- 중복 방지(기사 1건 안에서 같은 댓글은 1번만)
  UNIQUE KEY UK_T_NEWS_COMMENT__ARTICLE_HASH (ARTICLE_SEQ, COMMENT_HASH),

  -- FK: 뉴스글 일련번호
  -- ON DELETE CASCADE: 기사(T_NEWS_ARTICLE)가 삭제되면 해당 기사 댓글(T_NEWS_COMMENT)도 함께 삭제됨
  -- 결과적으로 run 삭제 -> 기사 삭제 -> 댓글 삭제로 연쇄 정리됨
  CONSTRAINT FK_T_NEWS_COMMENT__ARTICLE
    FOREIGN KEY (ARTICLE_SEQ) REFERENCES T_NEWS_ARTICLE (ARTICLE_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (5) 트렌드 키워드 최종 순위(T_TREND_KEYWORD_FINAL_RANK) 테이블 생성
-- 키워드 x 기간필터(TODAY/D7/D14/D30) 기준 "전체 기사수 합계 + 최종 순위" 저장
  CREATE TABLE IF NOT EXISTS T_TREND_KEYWORD_FINAL_RANK (
    FINAL_RANK_SEQ BIGINT NOT NULL AUTO_INCREMENT,
    TREND_RUN_SEQ BIGINT NOT NULL,
    KEYWORD_SEQ BIGINT NOT NULL,
    PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
    ARTICLE_COUNT INT NOT NULL,
    FINAL_RANK INT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- PK: 최종 순위 일련번호
    PRIMARY KEY (FINAL_RANK_SEQ),

    -- 같은 run + 키워드 + 기간 조합은 1행만 존재하도록
    UNIQUE KEY UK_T_KFR__RUN_KEYWORD_PERIOD (TREND_RUN_SEQ, KEYWORD_SEQ, PERIOD_FILTER),

    -- 조회 성능용 인덱스
    KEY IX_T_KFR__RUN_PERIOD (TREND_RUN_SEQ, PERIOD_FILTER),
    KEY IX_T_KFR__RUN_PERIOD_RANK (TREND_RUN_SEQ, PERIOD_FILTER, FINAL_RANK),

    -- FK: 트렌드 실행 일련번호
    -- 여기서도 마찬가지로 함께 삭제되도록 CASCADE 걸음
    CONSTRAINT FK_T_KFR__RUN
      FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
      ON UPDATE RESTRICT ON DELETE CASCADE,

    -- FK: 키워드 일련번호
    CONSTRAINT FK_T_KFR__KEYWORD
      FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
      ON UPDATE RESTRICT ON DELETE RESTRICT
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- 2. 데이터 분석 후 저장 테이블
-- (1) 기사량 통계(T_ANALYZE_MEDIA_STAT) 테이블 생성
-- AI 요약 섹션 위에 뜨는 기사 수/언론사/분석 기간 같은 통계 정보를 빠르게 보여주기 위해 사용하는 테이블
CREATE TABLE IF NOT EXISTS T_ANALYZE_MEDIA_STAT (
  STAT_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  MEDIA_CODE INT NOT NULL,
  PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
  ARTICLE_COUNT INT NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 통계 일련번호
  PRIMARY KEY (STAT_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_KMS__RUN (TREND_RUN_SEQ),
  KEY IX_T_KMS__KEYWORD (KEYWORD_SEQ),
  KEY IX_T_KMS__MEDIA (MEDIA_CODE),
  KEY IX_T_KMS__PERIOD (PERIOD_FILTER),

  -- 중복 방지
  UNIQUE KEY UK_T_KMS__RUN_KMP (TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER),

  -- FK: 트렌드 일련번호
  CONSTRAINT FK_T_KMS__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_KMS__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 언론사 코드
  CONSTRAINT FK_T_KMS__MEDIA
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (1)-2 Search interest timeline
-- - Stores keyword-level daily search-interest scores (0..100).
-- - Rows are managed by keyword/date/geo/search_property so the same keyword can accumulate history across runs.
-- - LAST_TREND_RUN_SEQ only tracks which run most recently refreshed the row.
CREATE TABLE IF NOT EXISTS T_ANALYZE_SEARCH_TIMELINE (
  TIMELINE_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  KEYWORD_SEQ BIGINT NOT NULL,
  LAST_TREND_RUN_SEQ BIGINT NULL,
  OBSERVED_DATE DATE NOT NULL,
  GEO_CODE VARCHAR(10) NOT NULL DEFAULT 'KR',
  SEARCH_PROPERTY VARCHAR(20) NOT NULL DEFAULT '',
  TIMEFRAME_LABEL VARCHAR(32) NOT NULL DEFAULT 'today 3-m',
  DATA_SOURCE VARCHAR(32) NOT NULL DEFAULT 'NAVER_DATALAB',
  INTEREST_SCORE INT NOT NULL DEFAULT 0,
  IS_PARTIAL BOOLEAN NOT NULL DEFAULT FALSE,
  FETCHED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (TIMELINE_SEQ),

  UNIQUE KEY UK_T_ASTT__KEYWORD_DATE_GSP (
    KEYWORD_SEQ,
    OBSERVED_DATE,
    GEO_CODE,
    SEARCH_PROPERTY
  ),

  KEY IX_T_ASTT__KEYWORD_DATE (KEYWORD_SEQ, OBSERVED_DATE),
  KEY IX_T_ASTT__LAST_RUN (LAST_TREND_RUN_SEQ),

  CONSTRAINT FK_T_ASTT__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT FK_T_ASTT__LAST_RUN
    FOREIGN KEY (LAST_TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (2)-1 AI 요약 헤더 (T_ANALYZE_AI_SUMMARY) 테이블 생성
-- 언론사/기간필터와 무관하게 키워드당 1개 요약만 저장(= run 단위로 1개)
-- 어떤 기사들을 사용했는지는 별도 매핑 테이블(T_ANALYZE_AI_SUMMARY_ARTICLE)에서 전부 추적
CREATE TABLE IF NOT EXISTS T_ANALYZE_AI_SUMMARY (
  SUMMARY_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  SUMMARY_TEXT TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 요약 일련번호
  PRIMARY KEY (SUMMARY_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_KAIS__RUN (TREND_RUN_SEQ),
  KEY IX_T_KAIS__KEYWORD (KEYWORD_SEQ),

  -- 같은 run + keyword 조합은 1행만 존재하도록(키워드당 단일 요약)
  UNIQUE KEY UK_T_KAIS__RUN_KEYWORD (TREND_RUN_SEQ, KEYWORD_SEQ),

  -- FK: 트렌드 실행 일련번호
  CONSTRAINT FK_T_KAIS__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_KAIS__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (2)-2 AI 요약 사용 기사 매핑(T_ANALYZE_AI_SUMMARY_ARTICLE) 테이블 생성
-- 요약 1건(SUMMARY_SEQ)에 사용된 기사 N건(ARTICLE_SEQ)을 전부 기록
-- 기사 입력 순서를 확인하기 위해 INPUT_ORDER를 채워 넣음
CREATE TABLE IF NOT EXISTS T_ANALYZE_AI_SUMMARY_ARTICLE (
  LINK_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  SUMMARY_SEQ BIGINT NOT NULL,
  ARTICLE_SEQ BIGINT NOT NULL,
  INPUT_ORDER INT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 매핑 일련번호
  PRIMARY KEY (LINK_SEQ),

  -- 중복 방지: 한 요약에 같은 기사 중복 연결 금지
  UNIQUE KEY UK_T_KAIS_ART__SUMMARY_ARTICLE (SUMMARY_SEQ, ARTICLE_SEQ),

  -- 입력 순서 중복 방지(한 요약 안에서 1,2,3... 유일)
  UNIQUE KEY UK_T_KAIS_ART__SUMMARY_ORDER (SUMMARY_SEQ, INPUT_ORDER),

  -- 조회 성능용 인덱스
  KEY IX_T_KAIS_ART__SUMMARY (SUMMARY_SEQ),
  KEY IX_T_KAIS_ART__ARTICLE (ARTICLE_SEQ),

  -- FK: 요약 일련번호 
  -- (연쇄 삭제) run 삭제 -> 요약 헤더 삭제 -> 매핑(LINK) 삭제
  CONSTRAINT FK_T_KAIS_ART__SUMMARY
    FOREIGN KEY (SUMMARY_SEQ) REFERENCES T_ANALYZE_AI_SUMMARY (SUMMARY_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 뉴스글 일련번호
  -- 원래는 run 삭제 -> 뉴스 글 삭제 -> 매핑 삭제 + run 삭제 -> 요약 헤더 삭제 -> 매핑 삭제 라서 다중 CASCADE 였는데
  -- 위에서 요약 헤더 삭제 시 매핑이 삭제되므로 이곳에선 CASCADE 없앰
  CONSTRAINT FK_T_KAIS_ART__ARTICLE
    FOREIGN KEY (ARTICLE_SEQ) REFERENCES T_NEWS_ARTICLE (ARTICLE_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (3) 감성 분석(T_ANALYZE_SENTIMENT)
-- 제목 기반 비율: *_PCT_TITLE
-- 본문 기반 비율: *_PCT_CONTENT
-- 여기서 제목/본문을 ENUM('TITLE','CONTENT'), ENUM('POSITIVE' ,'NEUTRAL', 'NEGATIVE')으로 할 수도 있었지만 그냥 따로 행 만듦
-- DECIMAL(전체 자리수, 소수점 자리수)
-- DECIMAL(5,2) => 최대 999.99까지 가능
-- DECIMAL(7,2) => 최대 99999.99까지 가능
-- DECIMAL(7,4) => 최대 999.9999까지 가능. 9999.999 같은건 안됨. 소수점은 무조건 4자리 확정이고 남은 3자리만 정수 자리 사용가능
CREATE TABLE IF NOT EXISTS T_ANALYZE_SENTIMENT (
  SENTIMENT_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  MEDIA_CODE INT NOT NULL DEFAULT 0,              
  PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
  POSITIVE_PCT_TITLE DECIMAL(5,2) NOT NULL DEFAULT 0,
  NEUTRAL_PCT_TITLE  DECIMAL(5,2) NOT NULL DEFAULT 0,
  NEGATIVE_PCT_TITLE DECIMAL(5,2) NOT NULL DEFAULT 0,
  POSITIVE_PCT_CONTENT DECIMAL(5,2) NOT NULL DEFAULT 0,
  NEUTRAL_PCT_CONTENT  DECIMAL(5,2) NOT NULL DEFAULT 0,
  NEGATIVE_PCT_CONTENT DECIMAL(5,2) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 감성 일련번호
  PRIMARY KEY (SENTIMENT_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_KSENT__RUN (TREND_RUN_SEQ),
  KEY IX_T_KSENT__KEYWORD (KEYWORD_SEQ),
  KEY IX_T_KSENT__MEDIA (MEDIA_CODE),

  -- 중복 방지
  UNIQUE KEY UK_T_KSENT__RUN_KMP (TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER),

  -- FK: 트렌드 일련번호
  CONSTRAINT FK_T_KSENT__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_KSENT__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 언론사 코드
  CONSTRAINT FK_T_KSENT__MEDIA
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (4) 언론사별 편향도 지수(T_ANALYZE_MEDIA_BIAS) 테이블 생성
-- 감성 분석 결과(T_ANALYZE_SENTIMENT)의 비율을 기반으로 파생 저장 -> 감성분석 테이블과 FK로 연결하지 않아도 된다 -> 그냥 파이썬 reader.py에서 해당 칼럼의 데이터만 읽어오면 됨
-- 제목/본문 편향도를 각각 저장 (-10 ~ +10)
-- 여기서 제목/본문을 ENUM('TITLE','CONTENT')으로 할 수도 있었지만 그냥 따로 행 만듦
CREATE TABLE IF NOT EXISTS T_ANALYZE_MEDIA_BIAS (
  BIAS_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  MEDIA_CODE INT NOT NULL,
  PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
  BIAS_SCORE_TITLE DECIMAL(5,2) NOT NULL DEFAULT 0,
  BIAS_SCORE_CONTENT DECIMAL(5,2) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 편향 일련번호
  PRIMARY KEY (BIAS_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_KBIAS__RUN (TREND_RUN_SEQ),
  KEY IX_T_KBIAS__KEYWORD (KEYWORD_SEQ),
  KEY IX_T_KBIAS__MEDIA (MEDIA_CODE),
  KEY IX_T_KBIAS__RUN_PERIOD (TREND_RUN_SEQ, PERIOD_FILTER),

  -- 같은 run + keyword + media + period 조합은 1행만
  UNIQUE KEY UK_T_KBIAS__RUN_KMP (TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER),

  -- FK: 트렌드 실행 일련번호
  CONSTRAINT FK_T_KBIAS__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_KBIAS__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 언론사 코드
  CONSTRAINT FK_T_KBIAS__MEDIA
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (5)-1 워드클라우드 헤더(T_ANALYZE_WORDCLOUD) 테이블 생성
-- 여기서는 제목/본문/댓글을 독립적인 행으로 만들지않고 ENUM('TITLE','CONTENT','COMMENT')으로 만듦
CREATE TABLE IF NOT EXISTS T_ANALYZE_WORDCLOUD (
  WC_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  MEDIA_CODE INT NOT NULL,
  PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
  WC_TYPE ENUM('TITLE','CONTENT','COMMENT') NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 워드클라우드 일련번호
  PRIMARY KEY (WC_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_WC__RUN (TREND_RUN_SEQ),
  KEY IX_T_WC__KEYWORD (KEYWORD_SEQ),
  KEY IX_T_WC__MEDIA (MEDIA_CODE),

  -- 중복 저장 방지
  UNIQUE KEY UK_T_WC__RUN_KMPW (TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER, WC_TYPE),

  -- FK: 트렌드 일련번호
  -- run 삭제 시 워드 클라우드 헤더도 함께 삭제
  CONSTRAINT FK_T_WC__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_WC__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 언론사 코드
  CONSTRAINT FK_T_WC__MEDIA
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (5)-2 워드클라우드 단어 아이템(T_ANALYZE_WORDCLOUD_ITEM)
CREATE TABLE IF NOT EXISTS T_ANALYZE_WORDCLOUD_ITEM (
  WC_ITEM_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  WC_SEQ BIGINT NOT NULL,
  RANK_NO INT NOT NULL,
  WORD_TEXT VARCHAR(80) NOT NULL,
  WEIGHT DECIMAL(10,4) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 단어 아이템 일련번호
  PRIMARY KEY (WC_ITEM_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_WCI__WC (WC_SEQ),

  -- 중복 방지
  UNIQUE KEY UK_T_WCI__WC_RANK (WC_SEQ, RANK_NO),
  UNIQUE KEY UK_T_WCI__WC_WORD (WC_SEQ, WORD_TEXT),

  -- FK: 워드클라우드 일련번호
  -- 연쇄 삭제: run 삭제 -> 워드 클라우드 헤더 삭제 -> 워드 클라우드 아이템 삭제
  CONSTRAINT FK_T_WCI__WC
    FOREIGN KEY (WC_SEQ) REFERENCES T_ANALYZE_WORDCLOUD (WC_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (6)-1 그래프 헤더(T_ANALYZE_CO_MENTION_GRAPH)
CREATE TABLE IF NOT EXISTS T_ANALYZE_CO_MENTION_GRAPH (
  GRAPH_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  TREND_RUN_SEQ BIGINT NOT NULL,
  KEYWORD_SEQ BIGINT NOT NULL,
  MEDIA_CODE INT NOT NULL,
  PERIOD_FILTER ENUM('TODAY','D7','D14','D30') NOT NULL,
  NODE_COUNT INT NOT NULL DEFAULT 0,
  EDGE_COUNT INT NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 그래프 일련번호
  PRIMARY KEY (GRAPH_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_GRAPH__RUN (TREND_RUN_SEQ),
  KEY IX_T_GRAPH__KEYWORD (KEYWORD_SEQ),
  KEY IX_T_GRAPH__MEDIA (MEDIA_CODE),

  -- 중복 방지
  UNIQUE KEY UK_T_GRAPH__RUN_KMP (TREND_RUN_SEQ, KEYWORD_SEQ, MEDIA_CODE, PERIOD_FILTER),

  -- FK: 트렌드 실행 일련번호
  -- 연쇄 삭제: run 삭제 -> 그래프 헤더 삭제 -> (그래프에 딸린) 엣지/노드 삭제
  CONSTRAINT FK_T_GRAPH__RUN
    FOREIGN KEY (TREND_RUN_SEQ) REFERENCES T_TREND_RUN (TREND_RUN_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 키워드 일련번호
  CONSTRAINT FK_T_GRAPH__KEYWORD
    FOREIGN KEY (KEYWORD_SEQ) REFERENCES T_TREND_KEYWORD_MASTER (KEYWORD_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 언론사 코드
  CONSTRAINT FK_T_GRAPH__MEDIA
    FOREIGN KEY (MEDIA_CODE) REFERENCES T_NEWS_MEDIA (MEDIA_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (6)-2 노드(T_ANALYZE_CO_MENTION_NODE)
CREATE TABLE IF NOT EXISTS T_ANALYZE_CO_MENTION_NODE (
  NODE_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  GRAPH_SEQ BIGINT NOT NULL,
  ENTITY_NAME VARCHAR(120) NOT NULL,
  ENTITY_TYPE ENUM('PERSON','ORG','LOCATION','ETC') NOT NULL DEFAULT 'ETC',
  NODE_WEIGHT DECIMAL(10,4) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 노드 일련번호
  PRIMARY KEY (NODE_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_NODE__GRAPH (GRAPH_SEQ),

  -- 중복 방지
  UNIQUE KEY UK_T_NODE__GRAPH_ENTITY (GRAPH_SEQ, ENTITY_NAME),

  -- FK: 그래프 일련번호
  CONSTRAINT FK_T_NODE__GRAPH
    FOREIGN KEY (GRAPH_SEQ) REFERENCES T_ANALYZE_CO_MENTION_GRAPH (GRAPH_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- (6)-3 엣지(T_ANALYZE_CO_MENTION_EDGE)
CREATE TABLE IF NOT EXISTS T_ANALYZE_CO_MENTION_EDGE (
  EDGE_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  GRAPH_SEQ BIGINT NOT NULL,
  FROM_NODE_SEQ BIGINT NOT NULL,
  TO_NODE_SEQ BIGINT NOT NULL,
  CO_MENTION_COUNT INT NOT NULL DEFAULT 0,
  EDGE_WEIGHT DECIMAL(10,4) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- PK: 엣지 일련번호
  PRIMARY KEY (EDGE_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_EDGE__GRAPH (GRAPH_SEQ),
  KEY IX_T_EDGE__FROM (FROM_NODE_SEQ),
  KEY IX_T_EDGE__TO (TO_NODE_SEQ),

  -- 중복 방지
  UNIQUE KEY UK_T_EDGE__GRAPH_FROM_TO (GRAPH_SEQ, FROM_NODE_SEQ, TO_NODE_SEQ),

  -- FK: 그래프 일련번호
  CONSTRAINT FK_T_EDGE__GRAPH
    FOREIGN KEY (GRAPH_SEQ) REFERENCES T_ANALYZE_CO_MENTION_GRAPH (GRAPH_SEQ)
    ON UPDATE RESTRICT ON DELETE CASCADE,

  -- FK: 노드 일련번호 (시작 노드)
  CONSTRAINT FK_T_EDGE__FROM_NODE
    FOREIGN KEY (FROM_NODE_SEQ) REFERENCES T_ANALYZE_CO_MENTION_NODE (NODE_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 노드 일련번호 (도착 노드)
  CONSTRAINT FK_T_EDGE__TO_NODE
    FOREIGN KEY (TO_NODE_SEQ) REFERENCES T_ANALYZE_CO_MENTION_NODE (NODE_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
