-- src/main/resources/db/migration/V1__create_accounts_tables.sql
-- Accounts: T_USER_LEVEL, T_USER, T_LOGIN_LOG
-- MySQL 8.x / utf8mb4 / InnoDB

SET NAMES utf8mb4;
SET time_zone = '+09:00';

-- (1) 회원 등급(T_USER_LEVEL) 테이블 생성
CREATE TABLE IF NOT EXISTS T_USER_LEVEL (
  GRADE_CODE TINYINT NOT NULL,
  GRADE_NAME VARCHAR(20) NOT NULL,

  -- PK: 회원 등급 번호
  PRIMARY KEY (GRADE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- (1)-1 초기 등급 시드 데이터 INSERT
INSERT INTO T_USER_LEVEL (GRADE_CODE, GRADE_NAME) VALUES
  (0, 'USER'),
  (1, 'ADMIN'),
  (2, 'SUPER_ADMIN')
ON DUPLICATE KEY UPDATE
  GRADE_NAME = VALUES(GRADE_NAME);

-- (2) 회원 (T_USER) 테이블 생성
CREATE TABLE IF NOT EXISTS T_USER (
  USER_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  USER_NAME VARCHAR(100) NOT NULL,
  USER_ID   VARCHAR(50)  NOT NULL,
  GRADE_CODE TINYINT     NOT NULL,
  EMAIL  VARCHAR(150) NOT NULL,
  GENDER CHAR(1)      NOT NULL,     -- 'M' / 'F'
  BIRTH_DATE DATE     NOT NULL,
  LAST_LOGIN_AT DATETIME NULL,
  JOINED_AT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  GRANTED_AT    DATETIME NULL,
  PASSWORD_CHANGED_AT DATETIME NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,

  -- PK: 회원 일련 번호
  PRIMARY KEY (USER_SEQ),

  -- 중복 방지
  UNIQUE KEY UK_T_USER__USER_ID (USER_ID),
  UNIQUE KEY UK_T_USER__EMAIL (EMAIL),

  -- 조회 성능용 인덱스
  KEY IX_T_USER__GRADE (GRADE_CODE),
  KEY IX_T_USER__JOINED_AT (JOINED_AT),

  -- FK: 회원 등급 번호
  CONSTRAINT FK_T_USER__GRADE
    FOREIGN KEY (GRADE_CODE) REFERENCES T_USER_LEVEL (GRADE_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- (3) 로그인 시도 기록 (T_LOGIN_LOG) 테이블 생성
CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
  LOGIN_LOG_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  INPUT_ID      VARCHAR(50) NOT NULL,
  ATTEMPTED_AT  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IS_SUCCESS    BOOLEAN     NOT NULL,
  IP_ADDRESS    VARCHAR(45) NOT NULL,  -- IPv4/IPv6
  USER_SEQ      BIGINT NULL,           -- 실패/미확인 사용자도 저장 가능
  USER_AGENT    TEXT NULL,

  -- PK: 회원 일련 번호
  PRIMARY KEY (LOGIN_LOG_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_LOGIN_LOG__ATTEMPTED_AT (ATTEMPTED_AT),
  KEY IX_T_LOGIN_LOG__INPUT_ID (INPUT_ID),
  KEY IX_T_LOGIN_LOG__USER_SEQ (USER_SEQ),

  -- FK: 회원 일련 번호
  CONSTRAINT FK_T_LOGIN_LOG__USER
    FOREIGN KEY (USER_SEQ) REFERENCES T_USER (USER_SEQ)
    ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
