-- src/main/resources/db/migration/V2__create_inquiries_tables.sql
-- Inquiries: T_INQUIRY_TYPE, T_INQUIRY
-- MySQL 8.x / utf8mb4 / InnoDB

SET NAMES utf8mb4;
SET time_zone = '+09:00';

-- (1) 문의 유형(T_INQUIRY_TYPE) 테이블 생성
CREATE TABLE IF NOT EXISTS T_INQUIRY_TYPE (
  TYPE_CODE   VARCHAR(20) NOT NULL,   
  TYPE_NAME   VARCHAR(50) NOT NULL,   
  SORT_ORDER  INT NOT NULL,         

  -- PK: 문의 유형 코드
  PRIMARY KEY (TYPE_CODE),

  -- 중복 방지
  UNIQUE KEY UX_T_INQUIRY_TYPE__TYPE_NAME (TYPE_NAME),

  -- 조회 성능용 인덱스
  KEY IX_T_INQUIRY_TYPE__SORT_ORDER (SORT_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- (1)-1 초기 문의 유형 Seed 삽입
INSERT INTO T_INQUIRY_TYPE (TYPE_CODE, TYPE_NAME, SORT_ORDER)
VALUES
  ('BUG_REPORT',      '오류 제보',   10),
  ('FEATURE_REQUEST', '기능 제안',   20),
  ('DATA_INQUIRY',    '데이터 문의', 30),
  ('ACCOUNT_LOGIN',   '계정/로그인', 40),
  ('ETC',             '기타',        50)
ON DUPLICATE KEY UPDATE
  TYPE_NAME  = VALUES(TYPE_NAME),
  SORT_ORDER = VALUES(SORT_ORDER);

-- (2) 문의글(T_INQUIRY) 테이블 생성
CREATE TABLE IF NOT EXISTS T_INQUIRY (
  INQUIRY_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  PROCESSED_SEQ BIGINT NULL,                
  TITLE         VARCHAR(200) NOT NULL,
  SUBMITTED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  IS_PROCESSED  BOOLEAN  NOT NULL DEFAULT FALSE,
  MESSAGE       TEXT NOT NULL,
  PROCESSED_AT  DATETIME NULL,
  ADMIN_MESSAGE TEXT NULL,
  INQUIRER_SEQ  BIGINT NOT NULL,             
  IS_PRIVATE    TINYINT(1) NOT NULL DEFAULT 0, -- 0=공개, 1=비공개(작성자+ADMIN만 열람)
  ANSWER_UPDATED_AT DATETIME NULL,             -- 관리자 답변 수정 시각
  TYPE_CODE     VARCHAR(20) NOT NULL,          -- 문의 유형 코드

  -- PK: 문의글 일련번호
  PRIMARY KEY (INQUIRY_SEQ),

  -- 조회 성능용 인덱스
  KEY IX_T_INQUIRY__SUBMITTED_AT (SUBMITTED_AT),
  KEY IX_T_INQUIRY__TYPE_CODE (TYPE_CODE),
  KEY IX_T_INQUIRY__IS_PROCESSED (IS_PROCESSED),
  KEY IX_T_INQUIRY__INQUIRER (INQUIRER_SEQ),
  KEY IX_T_INQUIRY__PROCESSED (PROCESSED_SEQ),

  -- FK: 문의자 일련 번호
  CONSTRAINT FK_T_INQUIRY__INQUIRER
    FOREIGN KEY (INQUIRER_SEQ) REFERENCES T_USER (USER_SEQ)
    ON UPDATE RESTRICT ON DELETE RESTRICT,

  -- FK: 처리자 일련 번호
  CONSTRAINT FK_T_INQUIRY__PROCESSED_BY
    FOREIGN KEY (PROCESSED_SEQ) REFERENCES T_USER (USER_SEQ)
    ON UPDATE RESTRICT ON DELETE SET NULL,

  -- FK: 문의 유형 코드
  CONSTRAINT FK_T_INQUIRY__TYPE
    FOREIGN KEY (TYPE_CODE) REFERENCES T_INQUIRY_TYPE (TYPE_CODE)
    ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
