DROP PROCEDURE IF EXISTS ADD_TREND_RUN_PUBLISH_STATUS;

DELIMITER $$

CREATE PROCEDURE ADD_TREND_RUN_PUBLISH_STATUS()
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T_TREND_RUN'
      AND COLUMN_NAME = 'RUN_STATUS'
  ) THEN
    ALTER TABLE T_TREND_RUN
      ADD COLUMN RUN_STATUS VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED' AFTER TOP_N;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T_TREND_RUN'
      AND COLUMN_NAME = 'COMPLETED_AT'
  ) THEN
    ALTER TABLE T_TREND_RUN
      ADD COLUMN COMPLETED_AT DATETIME NULL AFTER RUN_STATUS;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T_TREND_RUN'
      AND COLUMN_NAME = 'PUBLISHED_AT'
  ) THEN
    ALTER TABLE T_TREND_RUN
      ADD COLUMN PUBLISHED_AT DATETIME NULL AFTER COMPLETED_AT;
  END IF;

  UPDATE T_TREND_RUN
  SET RUN_STATUS = 'PUBLISHED',
      COMPLETED_AT = COALESCE(COMPLETED_AT, RUN_AT),
      PUBLISHED_AT = COALESCE(PUBLISHED_AT, RUN_AT)
  WHERE RUN_STATUS = 'PUBLISHED'
     OR RUN_STATUS IS NULL
     OR RUN_STATUS = '';

  ALTER TABLE T_TREND_RUN
    MODIFY COLUMN RUN_STATUS VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS';

  IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'T_TREND_RUN'
      AND INDEX_NAME = 'IX_T_TREND_RUN__STATUS_SEQ'
  ) THEN
    CREATE INDEX IX_T_TREND_RUN__STATUS_SEQ
      ON T_TREND_RUN (RUN_STATUS, TREND_RUN_SEQ);
  END IF;
END$$

CALL ADD_TREND_RUN_PUBLISH_STATUS()$$

DROP PROCEDURE IF EXISTS ADD_TREND_RUN_PUBLISH_STATUS$$

DELIMITER ;
