SET NAMES utf8mb4;
SET time_zone = '+09:00';

CREATE TABLE IF NOT EXISTS T_DAILY_VISITOR (
  VISITOR_DAILY_SEQ BIGINT NOT NULL AUTO_INCREMENT,
  VISIT_DATE DATE NOT NULL,
  VISITOR_KEY_HASH CHAR(64) NOT NULL,
  FIRST_VISITED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_VISITED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PAGE_VIEW_COUNT INT NOT NULL DEFAULT 1,
  IP_ADDRESS VARCHAR(45) NULL,
  USER_AGENT TEXT NULL,
  REFERRER VARCHAR(1024) NULL,
  ACCEPT_LANGUAGE VARCHAR(255) NULL,
  CLIENT_TIME_ZONE VARCHAR(64) NULL,
  SCREEN_WIDTH INT NULL,
  SCREEN_HEIGHT INT NULL,
  FIRST_PATH VARCHAR(512) NULL,
  LAST_PATH VARCHAR(512) NULL,

  PRIMARY KEY (VISITOR_DAILY_SEQ),
  UNIQUE KEY UK_T_DAILY_VISITOR__DATE_HASH (VISIT_DATE, VISITOR_KEY_HASH),
  KEY IX_T_DAILY_VISITOR__VISIT_DATE (VISIT_DATE),
  KEY IX_T_DAILY_VISITOR__LAST_VISITED_AT (LAST_VISITED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
